services:
  - type: web
    name: image-classifier-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: image-classifier-backend/Dockerfile
    buildContext: image-classifier-backend      # <-- Add this line
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    autoDeploy: true
    healthCheckPath: /


  - type: web
    name: image-classifier-frontend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: frontend/Dockerfile
    buildContext: frontend
    autoDeploy: true
    healthCheckPath: /
